Feature/hw three
xnagpa/react_playground pull request #3
Opened 2016-12-29 13:02 UTC by xnagpa

2017-01-12 06:31 UTC, index01d requested changes

2017-01-12 06:31 UTC, index01d commented on BlogList.js
> +        // iris data from R
rly?

2017-01-12 06:31 UTC, index01d commented on BlogList.js
> +    blog_entries[index].likes += 1;
здесь произошло изменение состояния. Нужно создать копию состояния.

2017-01-12 06:31 UTC, index01d commented on BlogList.js
> +    console.log(like_title)
rly?

2017-01-12 06:31 UTC, index01d commented on BlogList.js
> +    let like_title = (_.map(this.props.blog_entries, (entry, key) => (
для названий переменных лучше как везде использовать camelCase

2017-01-12 06:31 UTC, index01d commented on BlogList.js
> +        React.createElement(PieChart,{ columns: like_title}))
вместе с подготовкой данных лучше выделить в отдельный компонент

2017-01-12 10:44 UTC, index01d commented
а где собсна вопрос?

2017-01-12 11:09 UTC, xnagpa commented on BlogList.js
> +    blog_entries[index].likes += 1;
Я не очень понял(  
Я изменяю массив blog_entries, который болтается просто так вне всех компонентов. Строчкой ниже я изменяю состояние this.setState({blog_entries: blog_entries});. Копию какого состояния мне нужно создать? Зачем создавать копию состояния, если я все равно использую this.setState?

2017-01-12 13:56 UTC, index01d commented on BlogList.js
> +    blog_entries[index].likes += 1;
Копию объекта blog_entries, для того, чтобы не менять содержимое текущего состояния. Проще говоря: если после blog_entries[index].likes += 1; проверить this.state.blog_entries, то окажется, что изменение в состоянии уже сделано, чего быть не должно.

2017-01-13 07:01 UTC, index01d approved these changes

2017-01-18 06:18 UTC, merged