Feature/hw four
xnagpa/react_playground pull request #4
Opened 2017-01-18 06:19 UTC by xnagpa

2017-01-19 06:16 UTC, index01d requested changes
Если запустить `./node_modules/eslint/bin/eslint.js src/.`, то вернется много замечаний, которые нужно поправить (удалось ли настроить линтер в редакторе кода?); c3 отсутствует в зависимостях проекта.

2017-01-23 07:36 UTC, index01d requested changes
линтер все еще имеет 7 возражений; при открытии страницы в консоли можно увидеть ошибки в типах (propTypes); like соответственно не работает

2017-01-24 08:34 UTC, index01d requested changes
dist/bundle.js можно удалить, он более не нужен;
нужно внести исправление для линтера (на форуме коллеги дали правильный ответ); на диаграмме не меняются значения если лайкать посты. Внутри проекта желательно придерживаться единообразного подхода: JSX vs non-JSX, то есть допустимо и то и то, но пользоваться нужно каким-то конкретным подходом.

2017-01-24 08:34 UTC, index01d commented on index.html
> +    <script src="dist/bundle.js"></script>
здесь должно быть уже /assets/bundle.js; dist использовался для статической ручной сборки.

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +const ListPresenter = (props) => (
не совсем понятно почему presenter, но это замечание чисто стилистическое

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +          meta: entry.meta,
можно использовать pick из lodash

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +import _ from 'lodash';
import  { map } from 'lodash/collection';

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +      _.map(props.blogEntries, (entry) => (
просто map

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +      React.createElement('div',{},React.createElement('ul', {},
DOM.div, DOM.ul будет короче и опрятнее

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/PieChartPresenter.js
> +class PieChart extends React.Component {
не хватает методов деструкции на componentWillUnmount, componentWillReceiveProps на получение новых свойств

2017-01-24 08:34 UTC, index01d commented on src/components/widgets/blog/PieChartPresenter.js
> +    const likeTitle = (_.map(this.props.blogEntries, (entry) => (
должно делаться в контейнерном компоненте,  в нашем случае это был BlogPage. Неверно в одном модуле мешать контейнерную и презентационную логику.

2017-01-25 14:02 UTC, xnagpa commented on src/components/widgets/blog/ListPresenter.js
> +          meta: entry.meta,
В таком случае не получится впихнуть туда increaselikesHandler: props.increaseLikesHandler

2017-01-26 17:37 UTC, index01d requested changes
Семантик с одной стороны подключен, с другой - я не заметил, чтобы он где-то использовался; я бы предложил декомпозировать propTypes и свойства по-умолчанию в BlogItem по соответствующим компонента (то есть тип данных для картинки указать в Image и прокинуть его в BlogItem с помощью PropTypes.shape)

2017-01-26 17:37 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +          meta: entry.meta,
assign({}, pick, {всечтоугодно})

2017-01-26 17:37 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +      React.createElement('div',{},React.createElement('ul', {},
с одной стороны, с другой – Абрамова укусила муха и DOM-хелперы выпилят из React 16 в отдельный пакет (https://github.com/facebook/react/issues/8854) вместе с Legacy-createClass

2017-01-28 08:42 UTC, index01d approved these changes

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/Item.js
> +  image: Image.defaultProps,
можно тогда здесь и не прокидывать

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/Item.js
> +  meta: MetaData.defaultProps,
также можно тогда здесь не указывать

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
>  import React from 'react';
import React, { DOM } from 'react';

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
>  const { DOM } = React;
тогда здесь можно не деструктурировать

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
>  import _ from 'lodash';
нужно импортировать конкретные функции из lodash

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
>  import _ from 'lodash';
e.g.: `import { get } from 'lodash/object'`

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +const ListPresenter = (props) => (
({ blogEntries, increaseLikesHandler, likeTitles }) =>

2017-01-28 08:42 UTC, index01d commented on src/components/widgets/blog/ListPresenter.js
> +            {increaselikesHandler: props.increaseLikesHandler, key: entry.id,})
тогда здесь строка будет короче и опрятнее

2017-01-28 08:43 UTC, index01d approved these changes
Подтвердил, чтобы не затягивать процесс, но поработать еще есть над чем:)

2017-02-01 19:14 UTC, merged