Feature/hw five
xnagpa/react_playground pull request #5
Opened 2017-02-01 19:15 UTC by xnagpa

2017-02-04 09:12 UTC, index01d requested changes

2017-02-04 09:12 UTC, index01d commented on src/components/widgets/blog/elements/MetaData.js
>    return (React.createElement('div', {},
```
{ author && <TextBox /> }
```

2017-02-04 09:12 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
лучше тоже формировать функцией-хелпером, так как этот адрес может меняться

2017-02-04 09:12 UTC, index01d commented on src/components/Post.js
> +    const query = `http://localhost:3001${this.props.location.pathname}`;
Адрес до сервера лучше унести в константы

2017-02-04 09:12 UTC, index01d commented on src/components/BlogList.js
> +  fetchPosts(page) {
fetchPosts(page = 1)

2017-02-04 09:12 UTC, index01d commented on src/components/BlogList.js
> +  fetchPosts(page) {
тогда ниже можно убрать условия и дублирование кода

2017-02-04 09:12 UTC, index01d commented on src/components/widgets/blog/elements/PaginationMenu.js
> +      <Menu pagination>
будем считать, что это законно:)

2017-02-05 10:50 UTC, xnagpa commented on src/components/widgets/blog/elements/PaginationMenu.js
> +      <Menu pagination>
Я просто выдрал это из документации) А почему это может быть незаконно?

2017-02-06 09:34 UTC, index01d approved these changes
Под вынести в константы я имел ввиду сделать глобально файл constants/API и там конфигурировать информацию об API

2017-02-06 09:34 UTC, index01d commented on src/components/widgets/blog/elements/PaginationMenu.js
> +      <Menu pagination>
я имею ввиду что статически забиты пункты меню

2017-02-06 09:36 UTC, xnagpa commented on src/components/widgets/blog/elements/PaginationMenu.js
> +      <Menu pagination>
Аааа. Что правда, то правда.

2017-02-06 12:44 UTC, index01d approved these changes
Константы обычно называют БОЛЬШИМИ_БУКВАМИ:) [я_не_зануда]

В общем прув.

2017-02-12 15:20 UTC, merged