Adds like redux style
xnagpa/react_playground pull request #8
Opened 2017-03-26 12:53 UTC by xnagpa

2017-03-26 13:25 UTC, index01d requested changes
В контейнере нужно подключить созданный action
`import { like } from 'actions/Like';`
Далее добавить коллбэк в actionsToProps:
```
...
like: flowRight(dispatch, like)
...
```

Данное свойство получить например в компоненте ListPresenter и пробросить в качестве обработчика клика по кнопке. Если не хочется делать такой длинный проброс, то можно создать LikeContainer, сформировать там контейнер компонента при помощи функции connect и везде вместо Like отрисовывать LikeContainer.

2017-03-26 13:25 UTC, index01d commented on src/actions/Like.js
> +export function fetchPage(page) {
название нужно заменить:)

2017-04-06 12:34 UTC, xnagpa commented on src/routes/Blog.js
> +  prepareData: (store, query, params) => (
Не похоже, что эта строчка хоть когда-нибудь выполняется. 
Я не понимаю,  что она должна делать? Почему все работает, хотя prepareData ни разу не выполняется?

2017-04-06 22:02 UTC, index01d requested changes
Я не совсем понял куда ведет likePath, расскажи пожалуйста про это нововведение?

Что касается Like'a предлагаю всетаки обернуть его в LikeContainer и использовать на месте в BlogItem'e уже как `<LikeContainer id={item.id} />`.

2017-04-06 22:02 UTC, index01d commented on src/components/Post.js
> +  props.item.increaseLikesHandler = props.increaseLikesHandler;
почему не сделать это прямо в контейнере?

2017-04-07 07:08 UTC, xnagpa commented
Like path ведет на сервер, где происходит вот это 

application.put('/posts/:entry_id/likes', function(req, res){
   entries[req.params.entry_id].likes++;
   res.json(entries[req.params.entry_id]);
});

2017-04-07 07:49 UTC, xnagpa commented
У меня есть еще вопросы: 
Я поправил Pagination - оказалось что до этого я реализовал ее в обход redux.
Меня беспокоит момент: 
В конструкторе components/widgets/blog/PaginationMenu.js  я пишу 
 this.handleClick = bind(this.handleClick, this);  - значит handle_click получает контекст класса PaginationMenu. 
После этого я привязываю handleClick к кнопкам пагинации. 
<Button onClick={ this.handleClick.bind(this, entry) }>Страница {entry}</Button>
Неожиданно это работает, хотя я не понимаю почему.
 Что это за контекст? Куда я привязал handleClick?

2017-04-07 07:49 UTC, xnagpa commented on src/components/Post.js
> +  props.item.increaseLikesHandler = props.increaseLikesHandler;
Поправил

2017-04-07 08:16 UTC, index01d commented
> Like path ведет на сервер, где происходит вот это

Роут для этого не нужен тогда на стороне клиента.

2017-04-07 08:20 UTC, index01d commented
> Неожиданно это работает, хотя я не понимаю почему.
1) Нельзя делать bind в функции render()
2) Нельзя делать bind повторно
3) handleClick все еще в контексте текущего класса, но теперь получает в качестве перевого параметра entry

2017-04-07 10:27 UTC, xnagpa commented
> Роут для этого не нужен тогда на стороне клиента. С задачей вполне справится express-router
Я не понимаю(  Чтобы сделать запрос к серверному API нужен роут.  Для стягивания поста, пагинации,  и прочего тоже объявлены роуты.  Тогда почему мне не нужен роут для апдейта лайков в посте?

> Нельзя делать bind повторно
В таком случае, как мне передать entry в handleClick? Вытащить каким-то образом из ивента id элемента, у которого случился onClick? 

>  Что касается Like'a предлагаю всетаки обернуть его в LikeContainer и использовать на месте в BlogItem'e уже как <LikeContainer id={item.id} />.

Добавил LikeContainer.  На странице со всеми постами при нажатии на Like у всех лайков начинает отображаться одинаковая цифра.  Не понимаю, почему это происходит. 
На всякий случай ссылка на MR c серверной частью.   
https://github.com/xnagpa/blogServer/pull/1/files

2017-04-08 09:18 UTC, index01d commented
> Чтобы сделать запрос к серверному API нужен роут

Это утверждение неверно. Чтобы сделать запрос в случае нашего приложения нужен actionCreator и не более того. 

> В таком случае, как мне передать entry в handleClick? Вытащить каким-то образом из ивента id элемента, у которого случился onClick?

Нет, не так. Более того entry не должен передаваться в handleClick.

В приложении сейчас есть общая проблема связанная, возможно, с некоторым непониманием (продолжай задавать вопросы если и далее будет не ясно).

Во-первых пейджинация на данном этапе реализована неверно. Информация о пейджинации должна быть частью состояния списка записей. То есть условно иерархия в состоянии должна быть такова
```
state: {
  posts: {
    entries,
    pagination
  }
}
```

Управлять настройками и текущим состоянием пейджинации должен reducer списка постов. Нужно также убрать actionCreator Pagination и слить его в единый actionCreator fetchPosts, который должен принимать в качестве параметра номер страницы. Оба actionCreator'a сейчас по сути отвечают за одно и то же. Только 1 кидает запрос на /, другой на /posts/page/{n}. Можно всегда кидать запрос на /posts/page/{n}, где n по-умолчанию 1.

Роуты нужны только для конкретных страниц нашего приложения. То есть Список постов, Внутренняя поста и страница "О нас". Роуты Like и Pagination необходимо прибрать за ненадобностью. Номер страницы можно получить в prepareData роута Index. Вторым параметром prepareData получает query с GET-параметрами поступившего запроса запроса. То есть при обращении к `http://localhost:3000/?page=2` будет получен параметр `page: 2`. Если нужно все же организовать URL `http://localhost:3000/posts/page/2`, то можно создать еще один роут

```
const Posts = {
  path: '/posts/page/:number',
  component: PostsContainer,
  prepareData: (store, query, params) => (
    store.dispatch(fetchPosts(params.number))
  )
};
```

Для установки лайка достаточно реализовать actionCreator Like, обработать его action в reducer'e. Для того, чтобы кнопка получила необходимое значение нужно реализовать это в контейнере. Получится нечто типа:

BlogItem:
```
import LikeContainer from 'containers/LikeContainer';
...
render() {
  return (
    ...
    <LikeContainer id={item.id}>
    ...
  );
}
```

LikeContainer.js:
```
import { like } from 'actions/Like';
import LikeButton from 'elements/LikeButton';
import { find } from 'lodash';

const stateToProps = (state, ownProps) => ({
  likeCount: find(state.posts, { id: ownProps.id }).
});

const actionsToProps = (dispatch, ownProps) => ({
  onClick: () => { dispatch(like, ownProps.id) }
});

export default connect(stateToProps, actionsToProps)(LikeButton);
```

2017-04-11 07:54 UTC, index01d requested changes

2017-04-11 07:54 UTC, index01d commented on src/routes/Blog.js
> +    store.dispatch(fetchPosts(1))
здесь лучше получить для prepareData второй параметр и обработать параметр page из query. Иначе у страниц не будет ссылок.

2017-04-11 07:54 UTC, index01d commented on src/containers/LikeContainer.js
> +  let entry = state.like.entries && find(state.like.entries,
что-то как-то сложно получилось.
```
find(
  get(state, 'likes.entries', false) || get(state, 'posts.entries', []), 
  { id: ownProps.id }
)
```
а в каких случаях будут записи в like.entries и в posts.entries?

2017-04-11 08:09 UTC, xnagpa commented on src/containers/LikeContainer.js
> +  let entry = state.like.entries && find(state.like.entries,
В like.entries записи появляются если кто-то поставил like. 
 На сервер отправляется PUT.  Сервер отвечает обновленными записями. 

В posts.entries если кто-то просто запросил GET

2017-04-11 08:35 UTC, xnagpa commented on src/routes/Blog.js
> +    store.dispatch(fetchPosts(1))
типа того? 

  prepareData: (store, query) => (
    store.dispatch(fetchPosts(query['page'] || 1))
  )

2017-04-11 08:57 UTC, index01d commented on src/containers/LikeContainer.js
> +  let entry = state.like.entries && find(state.like.entries,
я бы порекомендовал тогда держать в like'ах не копию записи а только данные о количестве лайков дл сущностей. Тогда в reducer'е состояния like можно обрабатывать и успех загрузки постов (заполняя данные о лайках) и успех установки лайка (тогда сервер должен возвращать не копию записей а только информацию о лайках конкретной сущности)

2017-04-11 08:58 UTC, index01d commented on src/containers/LikeContainer.js
> +  let entry = state.like.entries && find(state.like.entries,
в таком случае не будет лишней условной логики

2017-04-11 08:58 UTC, index01d commented on src/routes/Blog.js
> +    store.dispatch(fetchPosts(1))
так точно

2017-04-11 13:08 UTC, xnagpa commented
Теперь c сервера приходит только структура с  [{id: 1, likes: 100500}]

2017-04-16 12:20 UTC, index01d approved these changes

2017-04-17 07:28 UTC, merged